remove duplicate rules with aggregate + add company name to block process + check for tools

diff --git a/hoyaf b/hoyaf
--- a/hoyaf
+++ b/hoyaf
@@ -13,12 +13,20 @@ blocklist=()
 unblocklist=()
 refresh="false"
 
+function checkForTool {
+    which $1 &> /dev/null
+    if [[ $? -ne 0 ]];then
+        echo "Required tool '$1' not found, please install it first"
+        exit 1
+    fi
+}
+
 function printUsage {
     echo "Horsemen of your altered future"
     echo
     echo "Block the four horsemen and other companies permanently using iptables"
     echo
-    echo "Usage: hoyaf [-b name] [-u name] [-l] [-h]"
+    echo "Usage: hoyaf [-b name] [-u name] [-r] [-l] [-h]"
     echo
     echo "Options:"
     echo "  -b/--block <name>    block the ip ranges of a company by name or ASN"
@@ -38,7 +46,11 @@ function printUsage {
 }
 
 function unblockByASN {
-    echo "Unblocking $1"
+    if [[ -z $2 ]];then
+        echo "Unblocking $1"
+    else
+        echo "Unblocking $2 ($1)"
+    fi
     file="/root/.cache/hoyaf/$1"
     if [[ -f $file ]];then
         count=0
@@ -60,11 +72,15 @@ function unblockByASN {
 
 function blockByASN {
     mkdir -p /root/.cache/hoyaf/
-    echo "Blocking $1"
+    if [[ -z $2 ]];then
+        echo "Blocking $1"
+    else
+        echo "Blocking $2 ($1)"
+    fi
     file="/root/.cache/hoyaf/$1"
     if [[ ! -f $file || ! -s $file || $refresh == "true" ]];then
         echo "  Downloading ip ranges from whois.radb.net"
-        proxychains whois -h whois.radb.net "!G$1" 2>/dev/null | grep -Eo "([0-9.]+){4}/[0-9]+" > $file
+        proxychains whois -h whois.radb.net "!G$1" 2>/dev/null | grep -Eo "([0-9.]+){4}/[0-9]+" | aggregate 2> /dev/null > $file
     else
         echo "  Using cached ranges, specify '--refresh' to download them anyway"
     fi
@@ -120,6 +136,11 @@ function listBlocked {
     exit
 }
 
+checkForTool iptables
+checkForTool whois
+checkForTool proxychains
+checkForTool tor
+checkForTool aggregate
 while [ "$#" -gt 0 ];do
     case "$1" in
         -b) blocklist=("${blocklist[@]}" "$2");shift 2;;
@@ -156,22 +177,22 @@ for block in "${blocklist[@]}" "${unblocklist[@]}";do
 done
 for unblock in "${unblocklist[@]}"; do
     if [[ ${unblock,,} == all ]];then
-        for company in "${companies[@]}";do
-            unblockByASN $company
+        for company in "${!companies[@]}";do
+            unblockByASN ${companies[$company]} $company
         done
     elif [[ ! -z "${companies[${unblock,,}]}" ]];then
-        unblockByASN "${companies[${unblock,,}]}"
+        unblockByASN "${companies[${unblock,,}]}" $unblock
     else
         unblockByASN ${unblock^^}
     fi
 done
 for block in "${blocklist[@]}"; do
     if [[ ${block,,} == all ]];then
-        for company in "${companies[@]}";do
-            blockByASN $company
+        for company in "${!companies[@]}";do
+            blockByASN ${companies[$company]} $company
         done
     elif [[ ! -z "${companies[${block,,}]}" ]];then
-        blockByASN "${companies[${block,,}]}"
+        blockByASN "${companies[${block,,}]}" $block
     else
         blockByASN ${block^^}
     fi
